# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AwJeez!' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AwJeez!
  pod 'Hero'
  pod 'Alamofire', '~> 4.7'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
  pod 'Arrow'
  pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift', :branch => 'develop'
  pod 'Kingfisher'
  pod 'RealmSwift'
  pod 'SwipeMenuViewController'
  pod 'EmptyDataSet-Swift', '~> 4.2.0'
end
